# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(877, 609)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBoxLFPpercent = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxLFPpercent.setEnabled(True)
        self.spinBoxLFPpercent.setMinimum(10)
        self.spinBoxLFPpercent.setMaximum(200)
        self.spinBoxLFPpercent.setSingleStep(5)
        self.spinBoxLFPpercent.setProperty("value", 50)
        self.spinBoxLFPpercent.setObjectName(_fromUtf8("spinBoxLFPpercent"))
        self.gridLayout.addWidget(self.spinBoxLFPpercent, 1, 5, 1, 1)
        self.labelLFP = QtGui.QLabel(self.centralwidget)
        self.labelLFP.setEnabled(True)
        self.labelLFP.setObjectName(_fromUtf8("labelLFP"))
        self.gridLayout.addWidget(self.labelLFP, 1, 4, 1, 1)
        self.labelStart = QtGui.QLabel(self.centralwidget)
        self.labelStart.setEnabled(True)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.gridLayout.addWidget(self.labelStart, 1, 0, 1, 1)
        self.pushButtonAdvance = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAdvance.setEnabled(True)
        self.pushButtonAdvance.setObjectName(_fromUtf8("pushButtonAdvance"))
        self.gridLayout.addWidget(self.pushButtonAdvance, 2, 2, 1, 1)
        self.lineEditStart = QtGui.QLineEdit(self.centralwidget)
        self.lineEditStart.setEnabled(True)
        self.lineEditStart.setObjectName(_fromUtf8("lineEditStart"))
        self.gridLayout.addWidget(self.lineEditStart, 1, 1, 1, 1)
        self.lineEditRecords = QtGui.QLineEdit(self.centralwidget)
        self.lineEditRecords.setEnabled(True)
        self.lineEditRecords.setObjectName(_fromUtf8("lineEditRecords"))
        self.gridLayout.addWidget(self.lineEditRecords, 2, 1, 1, 1)
        self.pushButtonGo = QtGui.QPushButton(self.centralwidget)
        self.pushButtonGo.setEnabled(True)
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.gridLayout.addWidget(self.pushButtonGo, 1, 2, 1, 1)
        self.labelRecords = QtGui.QLabel(self.centralwidget)
        self.labelRecords.setEnabled(True)
        self.labelRecords.setObjectName(_fromUtf8("labelRecords"))
        self.gridLayout.addWidget(self.labelRecords, 2, 0, 1, 1)
        self.labelFolder = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFolder.sizePolicy().hasHeightForWidth())
        self.labelFolder.setSizePolicy(sizePolicy)
        self.labelFolder.setText(_fromUtf8(""))
        self.labelFolder.setObjectName(_fromUtf8("labelFolder"))
        self.gridLayout.addWidget(self.labelFolder, 0, 0, 1, 3)
        self.pushButtonSet = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSet.setEnabled(True)
        self.pushButtonSet.setObjectName(_fromUtf8("pushButtonSet"))
        self.gridLayout.addWidget(self.pushButtonSet, 2, 5, 1, 1)
        self.pushButtonSpikes = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSpikes.setEnabled(False)
        self.pushButtonSpikes.setObjectName(_fromUtf8("pushButtonSpikes"))
        self.gridLayout.addWidget(self.pushButtonSpikes, 1, 6, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout.addWidget(self.pushButtonSave, 2, 6, 1, 1)
        self.pushButtonBack = QtGui.QPushButton(self.centralwidget)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.gridLayout.addWidget(self.pushButtonBack, 2, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuChannels = QtGui.QMenu(self.menubar)
        self.menuChannels.setObjectName(_fromUtf8("menuChannels"))
        self.menuTraces = QtGui.QMenu(self.menubar)
        self.menuTraces.setObjectName(_fromUtf8("menuTraces"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuRefs = QtGui.QMenu(self.menubar)
        self.menuRefs.setObjectName(_fromUtf8("menuRefs"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLFP = QtGui.QAction(MainWindow)
        self.actionLFP.setCheckable(True)
        self.actionLFP.setChecked(True)
        self.actionLFP.setObjectName(_fromUtf8("actionLFP"))
        self.actionShowBoxes = QtGui.QAction(MainWindow)
        self.actionShowBoxes.setCheckable(True)
        self.actionShowBoxes.setChecked(True)
        self.actionShowBoxes.setObjectName(_fromUtf8("actionShowBoxes"))
        self.actionShow_spikes = QtGui.QAction(MainWindow)
        self.actionShow_spikes.setCheckable(True)
        self.actionShow_spikes.setChecked(True)
        self.actionShow_spikes.setObjectName(_fromUtf8("actionShow_spikes"))
        self.actionSimple = QtGui.QAction(MainWindow)
        self.actionSimple.setCheckable(True)
        self.actionSimple.setChecked(True)
        self.actionSimple.setObjectName(_fromUtf8("actionSimple"))
        self.actionAdvance = QtGui.QAction(MainWindow)
        self.actionAdvance.setObjectName(_fromUtf8("actionAdvance"))
        self.actionBack = QtGui.QAction(MainWindow)
        self.actionBack.setObjectName(_fromUtf8("actionBack"))
        self.actionUse_wall_time = QtGui.QAction(MainWindow)
        self.actionUse_wall_time.setCheckable(True)
        self.actionUse_wall_time.setObjectName(_fromUtf8("actionUse_wall_time"))
        self.menuTraces.addAction(self.actionLFP)
        self.menuOptions.addAction(self.actionShowBoxes)
        self.menuOptions.addAction(self.actionShow_spikes)
        self.menuOptions.addAction(self.actionUse_wall_time)
        self.menubar.addAction(self.menuChannels.menuAction())
        self.menubar.addAction(self.menuRefs.menuAction())
        self.menubar.addAction(self.menuTraces.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelLFP.setText(_translate("MainWindow", "LFP scale %", None))
        self.labelStart.setText(_translate("MainWindow", "Start", None))
        self.pushButtonAdvance.setText(_translate("MainWindow", "Advance", None))
        self.lineEditStart.setText(_translate("MainWindow", "0", None))
        self.lineEditRecords.setText(_translate("MainWindow", "2048", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go", None))
        self.labelRecords.setText(_translate("MainWindow", "Samples", None))
        self.pushButtonSet.setText(_translate("MainWindow", "Set", None))
        self.pushButtonSpikes.setText(_translate("MainWindow", "Spikes", None))
        self.pushButtonSave.setText(_translate("MainWindow", "Save Image", None))
        self.pushButtonBack.setText(_translate("MainWindow", "Back", None))
        self.menuChannels.setTitle(_translate("MainWindow", "Channels", None))
        self.menuTraces.setTitle(_translate("MainWindow", "Traces", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuRefs.setTitle(_translate("MainWindow", "Montages", None))
        self.actionLFP.setText(_translate("MainWindow", "Raw", None))
        self.actionShowBoxes.setText(_translate("MainWindow", "Show detection boxes", None))
        self.actionShow_spikes.setText(_translate("MainWindow", "Show spikes", None))
        self.actionSimple.setText(_translate("MainWindow", "Simple", None))
        self.actionAdvance.setText(_translate("MainWindow", "Advance", None))
        self.actionAdvance.setShortcut(_translate("MainWindow", "Right", None))
        self.actionBack.setText(_translate("MainWindow", "Back", None))
        self.actionBack.setShortcut(_translate("MainWindow", "Left", None))
        self.actionUse_wall_time.setText(_translate("MainWindow", "Use wall time", None))

