# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created: Fri Oct 31 10:01:51 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(877, 609)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelYlimMin = QtGui.QLabel(self.centralwidget)
        self.labelYlimMin.setEnabled(True)
        self.labelYlimMin.setObjectName(_fromUtf8("labelYlimMin"))
        self.gridLayout.addWidget(self.labelYlimMin, 1, 3, 1, 1)
        self.spinBoxYlimLow = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxYlimLow.setEnabled(True)
        self.spinBoxYlimLow.setMinimum(-1000)
        self.spinBoxYlimLow.setMaximum(0)
        self.spinBoxYlimLow.setSingleStep(50)
        self.spinBoxYlimLow.setProperty("value", 0)
        self.spinBoxYlimLow.setObjectName(_fromUtf8("spinBoxYlimLow"))
        self.gridLayout.addWidget(self.spinBoxYlimLow, 1, 4, 1, 1)
        self.labelYNirMin = QtGui.QLabel(self.centralwidget)
        self.labelYNirMin.setObjectName(_fromUtf8("labelYNirMin"))
        self.gridLayout.addWidget(self.labelYNirMin, 1, 5, 1, 1)
        self.spinBoxYNirMin = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxYNirMin.setEnabled(True)
        self.spinBoxYNirMin.setMinimum(0)
        self.spinBoxYNirMin.setMaximum(500)
        self.spinBoxYNirMin.setSingleStep(5)
        self.spinBoxYNirMin.setProperty("value", 0)
        self.spinBoxYNirMin.setObjectName(_fromUtf8("spinBoxYNirMin"))
        self.gridLayout.addWidget(self.spinBoxYNirMin, 1, 6, 1, 1)
        self.labelLFP = QtGui.QLabel(self.centralwidget)
        self.labelLFP.setEnabled(True)
        self.labelLFP.setObjectName(_fromUtf8("labelLFP"))
        self.gridLayout.addWidget(self.labelLFP, 1, 7, 1, 1)
        self.spinBoxYlimHigh = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxYlimHigh.setEnabled(True)
        self.spinBoxYlimHigh.setMinimum(0)
        self.spinBoxYlimHigh.setMaximum(100000)
        self.spinBoxYlimHigh.setSingleStep(50)
        self.spinBoxYlimHigh.setProperty("value", 0)
        self.spinBoxYlimHigh.setObjectName(_fromUtf8("spinBoxYlimHigh"))
        self.gridLayout.addWidget(self.spinBoxYlimHigh, 2, 4, 1, 1)
        self.labelYNirMax = QtGui.QLabel(self.centralwidget)
        self.labelYNirMax.setObjectName(_fromUtf8("labelYNirMax"))
        self.gridLayout.addWidget(self.labelYNirMax, 2, 5, 1, 1)
        self.labelYlimMax = QtGui.QLabel(self.centralwidget)
        self.labelYlimMax.setEnabled(True)
        self.labelYlimMax.setObjectName(_fromUtf8("labelYlimMax"))
        self.gridLayout.addWidget(self.labelYlimMax, 2, 3, 1, 1)
        self.labelStart = QtGui.QLabel(self.centralwidget)
        self.labelStart.setEnabled(True)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.gridLayout.addWidget(self.labelStart, 1, 0, 1, 1)
        self.pushButtonAdvance = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAdvance.setEnabled(True)
        self.pushButtonAdvance.setObjectName(_fromUtf8("pushButtonAdvance"))
        self.gridLayout.addWidget(self.pushButtonAdvance, 2, 2, 1, 1)
        self.lineEditStart = QtGui.QLineEdit(self.centralwidget)
        self.lineEditStart.setEnabled(True)
        self.lineEditStart.setObjectName(_fromUtf8("lineEditStart"))
        self.gridLayout.addWidget(self.lineEditStart, 1, 1, 1, 1)
        self.lineEditRecords = QtGui.QLineEdit(self.centralwidget)
        self.lineEditRecords.setEnabled(True)
        self.lineEditRecords.setObjectName(_fromUtf8("lineEditRecords"))
        self.gridLayout.addWidget(self.lineEditRecords, 2, 1, 1, 1)
        self.pushButtonGo = QtGui.QPushButton(self.centralwidget)
        self.pushButtonGo.setEnabled(True)
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.gridLayout.addWidget(self.pushButtonGo, 1, 2, 1, 1)
        self.spinBoxYNirMax = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxYNirMax.setEnabled(True)
        self.spinBoxYNirMax.setMinimum(0)
        self.spinBoxYNirMax.setMaximum(500)
        self.spinBoxYNirMax.setSingleStep(5)
        self.spinBoxYNirMax.setProperty("value", 0)
        self.spinBoxYNirMax.setObjectName(_fromUtf8("spinBoxYNirMax"))
        self.gridLayout.addWidget(self.spinBoxYNirMax, 2, 6, 1, 1)
        self.labelRecords = QtGui.QLabel(self.centralwidget)
        self.labelRecords.setEnabled(True)
        self.labelRecords.setObjectName(_fromUtf8("labelRecords"))
        self.gridLayout.addWidget(self.labelRecords, 2, 0, 1, 1)
        self.labelFolder = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFolder.sizePolicy().hasHeightForWidth())
        self.labelFolder.setSizePolicy(sizePolicy)
        self.labelFolder.setText(_fromUtf8(""))
        self.labelFolder.setObjectName(_fromUtf8("labelFolder"))
        self.gridLayout.addWidget(self.labelFolder, 0, 0, 1, 3)
        self.spinBoxLFPpercent = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxLFPpercent.setEnabled(True)
        self.spinBoxLFPpercent.setMinimum(10)
        self.spinBoxLFPpercent.setMaximum(200)
        self.spinBoxLFPpercent.setSingleStep(5)
        self.spinBoxLFPpercent.setProperty("value", 50)
        self.spinBoxLFPpercent.setObjectName(_fromUtf8("spinBoxLFPpercent"))
        self.gridLayout.addWidget(self.spinBoxLFPpercent, 1, 8, 1, 1)
        self.pushButtonSet = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSet.setEnabled(True)
        self.pushButtonSet.setObjectName(_fromUtf8("pushButtonSet"))
        self.gridLayout.addWidget(self.pushButtonSet, 2, 8, 1, 1)
        self.pushButtonSpikes = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSpikes.setObjectName(_fromUtf8("pushButtonSpikes"))
        self.gridLayout.addWidget(self.pushButtonSpikes, 1, 9, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout.addWidget(self.pushButtonSave, 2, 9, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuChannels = QtGui.QMenu(self.menubar)
        self.menuChannels.setObjectName(_fromUtf8("menuChannels"))
        self.menuTraces = QtGui.QMenu(self.menubar)
        self.menuTraces.setObjectName(_fromUtf8("menuTraces"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLFP = QtGui.QAction(MainWindow)
        self.actionLFP.setCheckable(True)
        self.actionLFP.setChecked(True)
        self.actionLFP.setObjectName(_fromUtf8("actionLFP"))
        self.actionFiltered = QtGui.QAction(MainWindow)
        self.actionFiltered.setCheckable(True)
        self.actionFiltered.setChecked(True)
        self.actionFiltered.setObjectName(_fromUtf8("actionFiltered"))
        self.actionLogothetis = QtGui.QAction(MainWindow)
        self.actionLogothetis.setCheckable(True)
        self.actionLogothetis.setChecked(True)
        self.actionLogothetis.setObjectName(_fromUtf8("actionLogothetis"))
        self.actionShow_SWR_boxes = QtGui.QAction(MainWindow)
        self.actionShow_SWR_boxes.setCheckable(True)
        self.actionShow_SWR_boxes.setChecked(True)
        self.actionShow_SWR_boxes.setObjectName(_fromUtf8("actionShow_SWR_boxes"))
        self.actionShow_spikes = QtGui.QAction(MainWindow)
        self.actionShow_spikes.setCheckable(True)
        self.actionShow_spikes.setChecked(True)
        self.actionShow_spikes.setObjectName(_fromUtf8("actionShow_spikes"))
        self.actionYuval_Nir = QtGui.QAction(MainWindow)
        self.actionYuval_Nir.setCheckable(True)
        self.actionYuval_Nir.setChecked(True)
        self.actionYuval_Nir.setObjectName(_fromUtf8("actionYuval_Nir"))
        self.actionSimple = QtGui.QAction(MainWindow)
        self.actionSimple.setCheckable(True)
        self.actionSimple.setChecked(True)
        self.actionSimple.setObjectName(_fromUtf8("actionSimple"))
        self.menuTraces.addAction(self.actionLFP)
        self.menuTraces.addAction(self.actionFiltered)
        self.menuTraces.addAction(self.actionLogothetis)
        self.menuTraces.addAction(self.actionSimple)
        self.menuTraces.addAction(self.actionYuval_Nir)
        self.menuOptions.addAction(self.actionShow_SWR_boxes)
        self.menuOptions.addAction(self.actionShow_spikes)
        self.menubar.addAction(self.menuChannels.menuAction())
        self.menubar.addAction(self.menuTraces.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelYlimMin.setText(_translate("MainWindow", "max Y", None))
        self.labelYNirMin.setText(_translate("MainWindow", "Y. Nir min", None))
        self.labelLFP.setText(_translate("MainWindow", "LFP scale %", None))
        self.labelYNirMax.setText(_translate("MainWindow", "Y. Nir max", None))
        self.labelYlimMax.setText(_translate("MainWindow", "max Y", None))
        self.labelStart.setText(_translate("MainWindow", "Start", None))
        self.pushButtonAdvance.setText(_translate("MainWindow", "Advance", None))
        self.lineEditStart.setText(_translate("MainWindow", "0", None))
        self.lineEditRecords.setText(_translate("MainWindow", "2048", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go", None))
        self.labelRecords.setText(_translate("MainWindow", "Samples", None))
        self.pushButtonSet.setText(_translate("MainWindow", "Set", None))
        self.pushButtonSpikes.setText(_translate("MainWindow", "Spikes", None))
        self.pushButtonSave.setText(_translate("MainWindow", "Save Image", None))
        self.menuChannels.setTitle(_translate("MainWindow", "Channels", None))
        self.menuTraces.setTitle(_translate("MainWindow", "Traces", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.actionLFP.setText(_translate("MainWindow", "Raw", None))
        self.actionFiltered.setText(_translate("MainWindow", "Ripple (BP [80 180])", None))
        self.actionLogothetis.setText(_translate("MainWindow", "Logothetis (BP [5 200], LP 20)", None))
        self.actionShow_SWR_boxes.setText(_translate("MainWindow", "Show SWR boxes", None))
        self.actionShow_spikes.setText(_translate("MainWindow", "Show spikes", None))
        self.actionYuval_Nir.setText(_translate("MainWindow", "Yuval Nir", None))
        self.actionSimple.setText(_translate("MainWindow", "Simple", None))

