# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1096, 572)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.folderLabel = QtGui.QLabel(self.centralwidget)
        self.folderLabel.setText(_fromUtf8(""))
        self.folderLabel.setObjectName(_fromUtf8("folderLabel"))
        self.verticalLayout_2.addWidget(self.folderLabel)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.mainSplitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSplitter.sizePolicy().hasHeightForWidth())
        self.mainSplitter.setSizePolicy(sizePolicy)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName(_fromUtf8("mainSplitter"))
        self.layoutWidget = QtGui.QWidget(self.mainSplitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupComboBox = QtGui.QComboBox(self.layoutWidget)
        self.groupComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupComboBox.sizePolicy().hasHeightForWidth())
        self.groupComboBox.setSizePolicy(sizePolicy)
        self.groupComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.groupComboBox.setObjectName(_fromUtf8("groupComboBox"))
        self.horizontalLayout.addWidget(self.groupComboBox)
        self.artifactRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.artifactRadioButton.setObjectName(_fromUtf8("artifactRadioButton"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.artifactRadioButton)
        self.horizontalLayout.addWidget(self.artifactRadioButton)
        self.multiRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.multiRadioButton.setObjectName(_fromUtf8("multiRadioButton"))
        self.buttonGroup.addButton(self.multiRadioButton)
        self.horizontalLayout.addWidget(self.multiRadioButton)
        self.singleRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.singleRadioButton.setObjectName(_fromUtf8("singleRadioButton"))
        self.buttonGroup.addButton(self.singleRadioButton)
        self.horizontalLayout.addWidget(self.singleRadioButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listView = QtGui.QListView(self.layoutWidget)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout.addWidget(self.listView)
        self.tabWidget = QtGui.QTabWidget(self.mainSplitter)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.oneGroupTab = QtGui.QWidget()
        self.oneGroupTab.setObjectName(_fromUtf8("oneGroupTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.oneGroupTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonSave = QtGui.QPushButton(self.oneGroupTab)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout_3.addWidget(self.pushButtonSave)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.oneGroupLayout = QtGui.QVBoxLayout()
        self.oneGroupLayout.setObjectName(_fromUtf8("oneGroupLayout"))
        self.verticalLayout_5.addLayout(self.oneGroupLayout)
        self.tabWidget.addTab(self.oneGroupTab, _fromUtf8(""))
        self.allGroupsTab = QtGui.QWidget()
        self.allGroupsTab.setObjectName(_fromUtf8("allGroupsTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.allGroupsTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.autoassignPushButton = QtGui.QPushButton(self.allGroupsTab)
        self.autoassignPushButton.setObjectName(_fromUtf8("autoassignPushButton"))
        self.horizontalLayout_2.addWidget(self.autoassignPushButton)
        spacerItem2 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.allGroupsLayout = QtGui.QVBoxLayout()
        self.allGroupsLayout.setObjectName(_fromUtf8("allGroupsLayout"))
        self.verticalLayout_4.addLayout(self.allGroupsLayout)
        self.tabWidget.addTab(self.allGroupsTab, _fromUtf8(""))
        self.compareTab = QtGui.QWidget()
        self.compareTab.setObjectName(_fromUtf8("compareTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.compareTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.compareOneLabel = QtGui.QLabel(self.compareTab)
        self.compareOneLabel.setObjectName(_fromUtf8("compareOneLabel"))
        self.horizontalLayout_4.addWidget(self.compareOneLabel)
        self.groupOnecomboBox = QtGui.QComboBox(self.compareTab)
        self.groupOnecomboBox.setObjectName(_fromUtf8("groupOnecomboBox"))
        self.horizontalLayout_4.addWidget(self.groupOnecomboBox)
        self.compareTwoLabel = QtGui.QLabel(self.compareTab)
        self.compareTwoLabel.setObjectName(_fromUtf8("compareTwoLabel"))
        self.horizontalLayout_4.addWidget(self.compareTwoLabel)
        self.groupTwoComboBox = QtGui.QComboBox(self.compareTab)
        self.groupTwoComboBox.setObjectName(_fromUtf8("groupTwoComboBox"))
        self.horizontalLayout_4.addWidget(self.groupTwoComboBox)
        self.comparePlotpushButton = QtGui.QPushButton(self.compareTab)
        self.comparePlotpushButton.setObjectName(_fromUtf8("comparePlotpushButton"))
        self.horizontalLayout_4.addWidget(self.comparePlotpushButton)
        self.pushButtonMerge = QtGui.QPushButton(self.compareTab)
        self.pushButtonMerge.setObjectName(_fromUtf8("pushButtonMerge"))
        self.horizontalLayout_4.addWidget(self.pushButtonMerge)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.compareFigureLayout = QtGui.QVBoxLayout()
        self.compareFigureLayout.setObjectName(_fromUtf8("compareFigureLayout"))
        self.verticalLayout_3.addLayout(self.compareFigureLayout)
        self.tabWidget.addTab(self.compareTab, _fromUtf8(""))
        self.rastersTab = QtGui.QWidget()
        self.rastersTab.setObjectName(_fromUtf8("rastersTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.rastersTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonUpdateRasters = QtGui.QPushButton(self.rastersTab)
        self.pushButtonUpdateRasters.setEnabled(False)
        self.pushButtonUpdateRasters.setObjectName(_fromUtf8("pushButtonUpdateRasters"))
        self.horizontalLayout_5.addWidget(self.pushButtonUpdateRasters)
        self.label = QtGui.QLabel(self.rastersTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEditStimSelect = QtGui.QLineEdit(self.rastersTab)
        self.lineEditStimSelect.setEnabled(False)
        self.lineEditStimSelect.setObjectName(_fromUtf8("lineEditStimSelect"))
        self.horizontalLayout_5.addWidget(self.lineEditStimSelect)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.rasterLayout = QtGui.QVBoxLayout()
        self.rasterLayout.setObjectName(_fromUtf8("rasterLayout"))
        self.verticalLayout_8.addLayout(self.rasterLayout)
        self.tabWidget.addTab(self.rastersTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.mainSplitter)
        self.mainSplitter.raise_()
        self.folderLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuGroup = QtGui.QMenu(self.menubar)
        self.menuGroup.setObjectName(_fromUtf8("menuGroup"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionMakeArtifact = QtGui.QAction(MainWindow)
        self.actionMakeArtifact.setObjectName(_fromUtf8("actionMakeArtifact"))
        self.actionRelease = QtGui.QAction(MainWindow)
        self.actionRelease.setObjectName(_fromUtf8("actionRelease"))
        self.actionNextGroup = QtGui.QAction(MainWindow)
        self.actionNextGroup.setObjectName(_fromUtf8("actionNextGroup"))
        self.actionSelectSession = QtGui.QAction(MainWindow)
        self.actionSelectSession.setEnabled(False)
        self.actionSelectSession.setObjectName(_fromUtf8("actionSelectSession"))
        self.actionMarkCluster = QtGui.QAction(MainWindow)
        self.actionMarkCluster.setObjectName(_fromUtf8("actionMarkCluster"))
        self.actionNewGroup = QtGui.QAction(MainWindow)
        self.actionNewGroup.setEnabled(False)
        self.actionNewGroup.setObjectName(_fromUtf8("actionNewGroup"))
        self.actionAutoassign = QtGui.QAction(MainWindow)
        self.actionAutoassign.setObjectName(_fromUtf8("actionAutoassign"))
        self.actionActionGroupArtifact = QtGui.QAction(MainWindow)
        self.actionActionGroupArtifact.setObjectName(_fromUtf8("actionActionGroupArtifact"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpenJobs = QtGui.QAction(MainWindow)
        self.actionOpenJobs.setObjectName(_fromUtf8("actionOpenJobs"))
        self.actionNextJob = QtGui.QAction(MainWindow)
        self.actionNextJob.setObjectName(_fromUtf8("actionNextJob"))
        self.actionMergeAll = QtGui.QAction(MainWindow)
        self.actionMergeAll.setObjectName(_fromUtf8("actionMergeAll"))
        self.actionGotoJob = QtGui.QAction(MainWindow)
        self.actionGotoJob.setObjectName(_fromUtf8("actionGotoJob"))
        self.actionMerge = QtGui.QAction(MainWindow)
        self.actionMerge.setObjectName(_fromUtf8("actionMerge"))
        self.actionUpdateRasters = QtGui.QAction(MainWindow)
        self.actionUpdateRasters.setEnabled(False)
        self.actionUpdateRasters.setObjectName(_fromUtf8("actionUpdateRasters"))
        self.actionMerge_one_unit_groups = QtGui.QAction(MainWindow)
        self.actionMerge_one_unit_groups.setObjectName(_fromUtf8("actionMerge_one_unit_groups"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpenJobs)
        self.menuGroup.addAction(self.actionNewGroup)
        self.menuGroup.addAction(self.actionNextJob)
        self.menuGroup.addAction(self.actionGotoJob)
        self.menuGroup.addAction(self.actionMergeAll)
        self.menuGroup.addAction(self.actionMerge_one_unit_groups)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGroup.menuAction())
        self.compareOneLabel.setBuddy(self.groupOnecomboBox)
        self.compareTwoLabel.setBuddy(self.groupTwoComboBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.artifactRadioButton.setText(_translate("MainWindow", "Artifact", None))
        self.multiRadioButton.setText(_translate("MainWindow", "MU", None))
        self.singleRadioButton.setText(_translate("MainWindow", "SU", None))
        self.pushButtonSave.setText(_translate("MainWindow", "Save Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oneGroupTab), _translate("MainWindow", "One Group", None))
        self.autoassignPushButton.setText(_translate("MainWindow", "Autoassign", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.allGroupsTab), _translate("MainWindow", "All Groups", None))
        self.compareOneLabel.setText(_translate("MainWindow", "Group 1", None))
        self.compareTwoLabel.setText(_translate("MainWindow", "Group 2", None))
        self.comparePlotpushButton.setText(_translate("MainWindow", "Plot", None))
        self.pushButtonMerge.setText(_translate("MainWindow", "Merge", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compareTab), _translate("MainWindow", "Correlations", None))
        self.pushButtonUpdateRasters.setText(_translate("MainWindow", "Update", None))
        self.label.setText(_translate("MainWindow", "Paradigm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rastersTab), _translate("MainWindow", "Rasters", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuGroup.setTitle(_translate("MainWindow", "&Actions", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionMakeArtifact.setText(_translate("MainWindow", "makeArtifact", None))
        self.actionMakeArtifact.setToolTip(_translate("MainWindow", "Mark as Artifact", None))
        self.actionMakeArtifact.setShortcut(_translate("MainWindow", "A", None))
        self.actionRelease.setText(_translate("MainWindow", "release", None))
        self.actionRelease.setToolTip(_translate("MainWindow", "Release from group", None))
        self.actionRelease.setShortcut(_translate("MainWindow", "R", None))
        self.actionNextGroup.setText(_translate("MainWindow", "nextGroup", None))
        self.actionNextGroup.setToolTip(_translate("MainWindow", "Next Group", None))
        self.actionNextGroup.setShortcut(_translate("MainWindow", "N", None))
        self.actionSelectSession.setText(_translate("MainWindow", "Select &session", None))
        self.actionSelectSession.setShortcut(_translate("MainWindow", "Ctrl+U", None))
        self.actionMarkCluster.setText(_translate("MainWindow", "Mark cluster", None))
        self.actionMarkCluster.setShortcut(_translate("MainWindow", "Return", None))
        self.actionNewGroup.setText(_translate("MainWindow", "New &Group", None))
        self.actionNewGroup.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionAutoassign.setText(_translate("MainWindow", "Autoassign", None))
        self.actionAutoassign.setShortcut(_translate("MainWindow", "G", None))
        self.actionActionGroupArtifact.setText(_translate("MainWindow", "actionGroupArtifact", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionOpenJobs.setText(_translate("MainWindow", "Open &Jobs", None))
        self.actionNextJob.setText(_translate("MainWindow", "&Next Job", None))
        self.actionNextJob.setShortcut(_translate("MainWindow", "Ctrl+J", None))
        self.actionMergeAll.setText(_translate("MainWindow", "&Merge all", None))
        self.actionMergeAll.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionGotoJob.setText(_translate("MainWindow", "&Goto Job", None))
        self.actionMerge.setText(_translate("MainWindow", "Merge", None))
        self.actionUpdateRasters.setText(_translate("MainWindow", "updateRasters", None))
        self.actionMerge_one_unit_groups.setText(_translate("MainWindow", "Merge if just &1 cluster", None))
        self.actionMerge_one_unit_groups.setShortcut(_translate("MainWindow", "Ctrl+1", None))

