# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorter.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 572)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.folderLabel = QtWidgets.QLabel(self.centralwidget)
        self.folderLabel.setText("")
        self.folderLabel.setObjectName("folderLabel")
        self.verticalLayout_2.addWidget(self.folderLabel)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSplitter.sizePolicy().hasHeightForWidth())
        self.mainSplitter.setSizePolicy(sizePolicy)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.layoutWidget = QtWidgets.QWidget(self.mainSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.groupComboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupComboBox.sizePolicy().hasHeightForWidth())
        self.groupComboBox.setSizePolicy(sizePolicy)
        self.groupComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.groupComboBox.setObjectName("groupComboBox")
        self.horizontalLayout.addWidget(self.groupComboBox)
        self.artifactRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.artifactRadioButton.setObjectName("artifactRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.artifactRadioButton)
        self.horizontalLayout.addWidget(self.artifactRadioButton)
        self.multiRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.multiRadioButton.setObjectName("multiRadioButton")
        self.buttonGroup.addButton(self.multiRadioButton)
        self.horizontalLayout.addWidget(self.multiRadioButton)
        self.singleRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.singleRadioButton.setObjectName("singleRadioButton")
        self.buttonGroup.addButton(self.singleRadioButton)
        self.horizontalLayout.addWidget(self.singleRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.tabWidget = QtWidgets.QTabWidget(self.mainSplitter)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.oneGroupTab = QtWidgets.QWidget()
        self.oneGroupTab.setObjectName("oneGroupTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.oneGroupTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSave = QtWidgets.QPushButton(self.oneGroupTab)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_3.addWidget(self.pushButtonSave)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.oneGroupLayout = QtWidgets.QVBoxLayout()
        self.oneGroupLayout.setObjectName("oneGroupLayout")
        self.verticalLayout_5.addLayout(self.oneGroupLayout)
        self.tabWidget.addTab(self.oneGroupTab, "")
        self.allGroupsTab = QtWidgets.QWidget()
        self.allGroupsTab.setObjectName("allGroupsTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.allGroupsTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autoassignPushButton = QtWidgets.QPushButton(self.allGroupsTab)
        self.autoassignPushButton.setObjectName("autoassignPushButton")
        self.horizontalLayout_2.addWidget(self.autoassignPushButton)
        self.pushButtonTidy = QtWidgets.QPushButton(self.allGroupsTab)
        self.pushButtonTidy.setObjectName("pushButtonTidy")
        self.horizontalLayout_2.addWidget(self.pushButtonTidy)
        spacerItem2 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.allGroupsLayout = QtWidgets.QVBoxLayout()
        self.allGroupsLayout.setObjectName("allGroupsLayout")
        self.verticalLayout_4.addLayout(self.allGroupsLayout)
        self.tabWidget.addTab(self.allGroupsTab, "")
        self.compareTab = QtWidgets.QWidget()
        self.compareTab.setObjectName("compareTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.compareTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.compareOneLabel = QtWidgets.QLabel(self.compareTab)
        self.compareOneLabel.setObjectName("compareOneLabel")
        self.horizontalLayout_4.addWidget(self.compareOneLabel)
        self.groupOnecomboBox = QtWidgets.QComboBox(self.compareTab)
        self.groupOnecomboBox.setObjectName("groupOnecomboBox")
        self.horizontalLayout_4.addWidget(self.groupOnecomboBox)
        self.compareTwoLabel = QtWidgets.QLabel(self.compareTab)
        self.compareTwoLabel.setObjectName("compareTwoLabel")
        self.horizontalLayout_4.addWidget(self.compareTwoLabel)
        self.groupTwoComboBox = QtWidgets.QComboBox(self.compareTab)
        self.groupTwoComboBox.setObjectName("groupTwoComboBox")
        self.horizontalLayout_4.addWidget(self.groupTwoComboBox)
        self.comparePlotpushButton = QtWidgets.QPushButton(self.compareTab)
        self.comparePlotpushButton.setObjectName("comparePlotpushButton")
        self.horizontalLayout_4.addWidget(self.comparePlotpushButton)
        self.pushButtonMerge = QtWidgets.QPushButton(self.compareTab)
        self.pushButtonMerge.setObjectName("pushButtonMerge")
        self.horizontalLayout_4.addWidget(self.pushButtonMerge)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.compareFigureLayout = QtWidgets.QVBoxLayout()
        self.compareFigureLayout.setObjectName("compareFigureLayout")
        self.verticalLayout_3.addLayout(self.compareFigureLayout)
        self.tabWidget.addTab(self.compareTab, "")
        self.rastersTab = QtWidgets.QWidget()
        self.rastersTab.setObjectName("rastersTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.rastersTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonUpdateRasters = QtWidgets.QPushButton(self.rastersTab)
        self.pushButtonUpdateRasters.setEnabled(False)
        self.pushButtonUpdateRasters.setObjectName("pushButtonUpdateRasters")
        self.horizontalLayout_5.addWidget(self.pushButtonUpdateRasters)
        self.label = QtWidgets.QLabel(self.rastersTab)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEditStimSelect = QtWidgets.QLineEdit(self.rastersTab)
        self.lineEditStimSelect.setEnabled(False)
        self.lineEditStimSelect.setObjectName("lineEditStimSelect")
        self.horizontalLayout_5.addWidget(self.lineEditStimSelect)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.rasterLayout = QtWidgets.QVBoxLayout()
        self.rasterLayout.setObjectName("rasterLayout")
        self.verticalLayout_8.addLayout(self.rasterLayout)
        self.tabWidget.addTab(self.rastersTab, "")
        self.verticalLayout_2.addWidget(self.mainSplitter)
        self.mainSplitter.raise_()
        self.folderLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuGroup = QtWidgets.QMenu(self.menubar)
        self.menuGroup.setObjectName("menuGroup")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionMakeArtifact = QtWidgets.QAction(MainWindow)
        self.actionMakeArtifact.setObjectName("actionMakeArtifact")
        self.actionRelease = QtWidgets.QAction(MainWindow)
        self.actionRelease.setObjectName("actionRelease")
        self.actionNextGroup = QtWidgets.QAction(MainWindow)
        self.actionNextGroup.setObjectName("actionNextGroup")
        self.actionSelectSession = QtWidgets.QAction(MainWindow)
        self.actionSelectSession.setEnabled(False)
        self.actionSelectSession.setObjectName("actionSelectSession")
        self.actionMarkCluster = QtWidgets.QAction(MainWindow)
        self.actionMarkCluster.setObjectName("actionMarkCluster")
        self.actionNewGroup = QtWidgets.QAction(MainWindow)
        self.actionNewGroup.setEnabled(False)
        self.actionNewGroup.setObjectName("actionNewGroup")
        self.actionAutoassign = QtWidgets.QAction(MainWindow)
        self.actionAutoassign.setObjectName("actionAutoassign")
        self.actionActionGroupArtifact = QtWidgets.QAction(MainWindow)
        self.actionActionGroupArtifact.setObjectName("actionActionGroupArtifact")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpenJobs = QtWidgets.QAction(MainWindow)
        self.actionOpenJobs.setObjectName("actionOpenJobs")
        self.actionNextJob = QtWidgets.QAction(MainWindow)
        self.actionNextJob.setObjectName("actionNextJob")
        self.actionMergeAll = QtWidgets.QAction(MainWindow)
        self.actionMergeAll.setObjectName("actionMergeAll")
        self.actionGotoJob = QtWidgets.QAction(MainWindow)
        self.actionGotoJob.setObjectName("actionGotoJob")
        self.actionMerge = QtWidgets.QAction(MainWindow)
        self.actionMerge.setObjectName("actionMerge")
        self.actionUpdateRasters = QtWidgets.QAction(MainWindow)
        self.actionUpdateRasters.setEnabled(False)
        self.actionUpdateRasters.setObjectName("actionUpdateRasters")
        self.actionMerge_one_unit_groups = QtWidgets.QAction(MainWindow)
        self.actionMerge_one_unit_groups.setObjectName("actionMerge_one_unit_groups")
        self.actionTidyGroups = QtWidgets.QAction(MainWindow)
        self.actionTidyGroups.setObjectName("actionTidyGroups")
        self.actionSave_to_Matfile = QtWidgets.QAction(MainWindow)
        self.actionSave_to_Matfile.setObjectName("actionSave_to_Matfile")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpenJobs)
        self.menuGroup.addAction(self.actionNewGroup)
        self.menuGroup.addAction(self.actionNextJob)
        self.menuGroup.addAction(self.actionGotoJob)
        self.menuGroup.addAction(self.actionMergeAll)
        self.menuGroup.addAction(self.actionMerge_one_unit_groups)
        self.menuGroup.addAction(self.actionSave_to_Matfile)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGroup.menuAction())
        self.compareOneLabel.setBuddy(self.groupOnecomboBox)
        self.compareTwoLabel.setBuddy(self.groupTwoComboBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.artifactRadioButton.setText(_translate("MainWindow", "Artifact"))
        self.multiRadioButton.setText(_translate("MainWindow", "MU"))
        self.singleRadioButton.setText(_translate("MainWindow", "SU"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.oneGroupTab), _translate("MainWindow", "One Group"))
        self.autoassignPushButton.setText(_translate("MainWindow", "Autoassign"))
        self.pushButtonTidy.setText(_translate("MainWindow", "Tidy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.allGroupsTab), _translate("MainWindow", "All Groups"))
        self.compareOneLabel.setText(_translate("MainWindow", "Group 1"))
        self.compareTwoLabel.setText(_translate("MainWindow", "Group 2"))
        self.comparePlotpushButton.setText(_translate("MainWindow", "Plot"))
        self.pushButtonMerge.setText(_translate("MainWindow", "Merge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compareTab), _translate("MainWindow", "Correlations"))
        self.pushButtonUpdateRasters.setText(_translate("MainWindow", "Update"))
        self.label.setText(_translate("MainWindow", "Paradigm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rastersTab), _translate("MainWindow", "Rasters"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuGroup.setTitle(_translate("MainWindow", "&Actions"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionMakeArtifact.setText(_translate("MainWindow", "makeArtifact"))
        self.actionMakeArtifact.setToolTip(_translate("MainWindow", "Mark as Artifact"))
        self.actionMakeArtifact.setShortcut(_translate("MainWindow", "A"))
        self.actionRelease.setText(_translate("MainWindow", "release"))
        self.actionRelease.setToolTip(_translate("MainWindow", "Release from group"))
        self.actionRelease.setShortcut(_translate("MainWindow", "R"))
        self.actionNextGroup.setText(_translate("MainWindow", "nextGroup"))
        self.actionNextGroup.setToolTip(_translate("MainWindow", "Next Group"))
        self.actionNextGroup.setShortcut(_translate("MainWindow", "N"))
        self.actionSelectSession.setText(_translate("MainWindow", "Select &session"))
        self.actionSelectSession.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionMarkCluster.setText(_translate("MainWindow", "Mark cluster"))
        self.actionMarkCluster.setShortcut(_translate("MainWindow", "Return"))
        self.actionNewGroup.setText(_translate("MainWindow", "New &Group"))
        self.actionNewGroup.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionAutoassign.setText(_translate("MainWindow", "Autoassign"))
        self.actionAutoassign.setShortcut(_translate("MainWindow", "G"))
        self.actionActionGroupArtifact.setText(_translate("MainWindow", "actionGroupArtifact"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpenJobs.setText(_translate("MainWindow", "Open &Jobs"))
        self.actionNextJob.setText(_translate("MainWindow", "&Next Job"))
        self.actionNextJob.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionMergeAll.setText(_translate("MainWindow", "&Merge all"))
        self.actionMergeAll.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionGotoJob.setText(_translate("MainWindow", "&Goto Job"))
        self.actionMerge.setText(_translate("MainWindow", "Merge"))
        self.actionUpdateRasters.setText(_translate("MainWindow", "updateRasters"))
        self.actionMerge_one_unit_groups.setText(_translate("MainWindow", "Merge if just &1 cluster"))
        self.actionMerge_one_unit_groups.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionTidyGroups.setText(_translate("MainWindow", "tidyGroups"))
        self.actionSave_to_Matfile.setText(_translate("MainWindow", "Export times to matfile"))
        self.actionSave_to_Matfile.setShortcut(_translate("MainWindow", "Ctrl+E"))
